# Generated by Django 5.1.5 on 2026-08-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='arcexecution',
            name='arco_unico_por_corrida',
        ),
        migrations.RemoveConstraint(
            model_name='assignmentresult',
            name='asignacion_unica_por_corrida',
        ),
        migrations.RemoveConstraint(
            model_name='costcharge',
            name='costo_unico_por_corrida',
        ),
        migrations.RemoveConstraint(
            model_name='decisionalternative',
            name='alternativa_unica_por_corrida',
        ),
        migrations.RemoveConstraint(
            model_name='inventorysnapshot',
            name='inventario_unico_por_dia_ubicacion_producto',
        ),
        migrations.RemoveConstraint(
            model_name='resourcecapacitysnapshot',
            name='capacidad_unica_por_dia_recurso_ubicacion',
        ),
        migrations.AddIndex(
            model_name='arcexecution',
            index=models.Index(fields=['simulation_run', 'id_evento_arco'], name='core_arcexe_simulat_c0f231_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentresult',
            index=models.Index(fields=['simulation_run', 'id_asignacion'], name='core_assign_simulat_62d0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='costcharge',
            index=models.Index(fields=['simulation_run', 'id_costo'], name='core_costch_simulat_8ea944_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionalternative',
            index=models.Index(fields=['simulation_run', 'id_alternativa'], name='core_decisi_simulat_0d9b44_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysnapshot',
            index=models.Index(fields=['simulation_run', 'ubicacion', 'producto'], name='core_invent_simulat_0cfa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcecapacitysnapshot',
            index=models.Index(fields=['simulation_run', 'dia'], name='core_resour_simulat_417805_idx'),
        ),
    ]
