# Generated by Django 5.1.5 on 2026-08-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_quitar_unicidad_de_filas_de_auditoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="arcexecution",
            name="fecha_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="arcexecution",
            name="fecha_inicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignmentresult",
            name="fecha_asignacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="costcharge",
            name="fecha",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="decisionalternative",
            name="fecha",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="decisionalternative",
            name="fecha_cutoff",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventorysnapshot",
            name="fecha",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resourcecapacitysnapshot",
            name="fecha",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="fecha_inicio_campania",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="costcharge",
            index=models.Index(
                fields=["simulation_run", "fecha"],
                name="core_costch_simulat_84ee7c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorysnapshot",
            index=models.Index(
                fields=["simulation_run", "fecha"],
                name="core_invent_simulat_c374eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resourcecapacitysnapshot",
            index=models.Index(
                fields=["simulation_run", "fecha"],
                name="core_resour_simulat_30a5f9_idx",
            ),
        ),
    ]
