# Generated by Django 5.1.5 on 2026-08-15 22:34

from django.db import migrations, models


def _promover_desde_extra(apps, schema_editor):
    """ADR-T05 (MOD v6): `material`/`proveedor` estaban declarados en el esquema desde siempre,
    asi que las corridas ya importadas los tienen guardados en `extra` (FilaAuditoria) sin poder
    filtrarlos. Copiarlos a la columna nueva evita tener que reimportar nada."""
    CostCharge = apps.get_model("core", "CostCharge")
    AssignmentResult = apps.get_model("core", "AssignmentResult")

    for fila in CostCharge.objects.exclude(extra={}).iterator():
        material = fila.extra.get("material", "")
        proveedor = fila.extra.get("proveedor", "")
        if material or proveedor:
            fila.material = material
            fila.proveedor = proveedor
            fila.save(update_fields=["material", "proveedor"])

    for fila in AssignmentResult.objects.exclude(extra={}).iterator():
        material = fila.extra.get("material", "")
        if material:
            fila.material = material
            fila.save(update_fields=["material"])


def _revertir(apps, schema_editor):
    """No hay nada que deshacer: los datos siguen en `extra`, se puede recalcular siempre."""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_fecha_calendario_adr_064_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentresult",
            name="material",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="costcharge",
            name="material",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="costcharge",
            name="proveedor",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RunPython(_promover_desde_extra, _revertir),
    ]
